---
title: "calltaxi_ys"
author: "YS YOON"
date: "2019년 4월 29일"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## **중간보고 자료의 제한점**

- 건별 자료에 대한 정보를 얻을 수 없어 규명하고자 했던 문제를 탐색하는데 제한이 있음.



## **추가 자료 활용을 통해 규명하고자 하는 문제**

- 장애인 콜택시 주요 목적지 시각화
- 장애인 콜택시 주요 목적지를 needs에 따라 `clustering` 
- 장애인 콜택시 수요자의 지역 특성 분석(구별 장애인 시설/ 병원 시설과 연계)
- 장애인 콜택시 수요자의 주요 이용 시간 분석
- 구별 장애인 콜택시 수급 불균형을 파악/ 수급 불균형을 초래하는 `요인 분석`(ex: 날씨, 요일 등) 

## **향후 진행일정**

|항목 및 날짜| 4월4주 | 5월 1주 |5월 2주|5월 3주|5월 4주|5월 5주|6월 1주|6월 2주|6월 3주|
|------------|:------:|:-------:|:-----:|:-----:|:-----:|:-----:|:-----:|:-----:|:-----:|
|데이터 확보 |`--` |||||||||
|데이터 클리닝| |`--`|`--`|`--`||||||
|데이터 분석 | ||`--`|`--`||||||
|선행분석방법론 검토| |||`--`|`--`|`--`||||
|데이터 시각화| |||`--`|`--`|`--`||||
|데이터 해석| |||`--`|`--`|`--`|`--`|||
|paper 작성| |||||||`--`|`--`|`--`|

## **기대효과**
+ 장애인 콜택시 주요 목적지 시각화/ 목적지를 needs에 따라 clustering 


    + 현재 단일 서비스 시스템이 아니라 장애인 콜택시 이용자의 needs(여가생활, 학교, 병원 등)에 따른 다양한 서비스(수요와 공급의 불균형을 해소하는 방안) 개발의 기초자료를 제공하여 장애인 콜택시 도입 본연의 목적을 효과적으로 달성할 수 있을 것으로 기대됨.

+ 장애인 콜택시 수요자의 지역 특성 분석(구별 장애인 시설/ 병원 시설과 연계)


    + 통계청의 서울시 구별 장애인구, 장애시설 통계, 지리정보시스템을 활용하여 장애인 콜택시 서비스 이용행태 및 요인을 다층적(multilevel)으로 분석함으로써, 장애인 이동권 증진 정책 수립의 실증적 근거 제공

+ 장애인 콜택시 수요자의 주요 이용 시간 분석

    
+ 구별 장애인 콜택시 수급 불균형을 파악/ 수급 불균형을 초래하는 요인 분석(ex: 날씨, 요일 등) 


    + 이용자가 몰리는 시간 및 장소 분석 자료를 활용해 가장 적절한 시간 등을 추천해 장애인 콜택시 이용의 효율성을 높일 수 있을 것으로 기대함.
    + 데이터 분석을 통한 민간 복지 품질 제고 및 우수 업체 참여를 통한 경쟁 유도(타다, 쏘카)


    + 지자체별 다양한 복지프로그램이 시행되고 있는데, 지자체 특성상 복지 수혜자가 지역적으로 한정되어 있음. 많은 경우 복지의 필요성과 지역적 한계가 불일치하는 문제를 해결하기 위해 지자체간 복지프로그램 공유/교환 방법에 관한 논의의 시발점을 제공함.

## 이를통해

- 공급자 관점이 아닌 수요자 관점의 needs 파악 및 대응 방안 사전 수립.
- 공공 데이터 활용을 통한 정보 생산을 위한 수집 데이터 자료(변수/제공방법) 등에 관한 제언

